import type { Metadata } from 'next'
import { Inter, Bowlby_One_SC } from 'next/font/google'
import './globals.css'
import Header from './components/Header'

const inter = Inter({ subsets: ['latin'] })
 
const bowlby = Bowlby_One_SC({
  weight: '400',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={bowlby.className}>
        <Header />
        {children}
        </body>
    </html>
  )
}
